#!/usr/bin/env bash

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

#set -euo pipefail
LC_ALL=C
LC_NUMERIC=C

include () {
    [[ -f "$1" ]] && source "$1"
}

include /var/local/machine/plugins/colors.sh
include /var/local/machine/plugins/functions.sh

fail2ban_client=$(systemctl is-active fail2ban)

[[ $fail2ban_client == "active" ]] || exit 0

# fail2ban-client status to get all jails, takes about ~70ms
jails=($(fail2ban-client status | grep "Jail list:" | sed "s/ //g" | awk '{split($2,a,",");for(i in a) print a[i]}'))

out="jail,failed,total,banned,total\n"

for jail in ${jails[@]}; do
    # slow because fail2ban-client has to be called for every jail (~70ms per jail)
    status=$(fail2ban-client status ${jail})
    failed=$(echo "$status" | grep -ioP '(?<=Currently failed:\t)[[:digit:]]+')
    totalfailed=$(echo "$status" | grep -ioP '(?<=Total failed:\t)[[:digit:]]+')
    banned=$(echo "$status" | grep -ioP '(?<=Currently banned:\t)[[:digit:]]+')
    totalbanned=$(echo "$status" | grep -ioP '(?<=Total banned:\t)[[:digit:]]+')
    out+="$jail,$failed,$totalfailed,$banned,$totalbanned\n"
done

printf "\nfail2ban status:\n"
printf $out | column -ts $',' | sed -e 's/^/  /'