---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Configure chrony
  template:
    src: 'etc/chrony/chrony.conf.j2'
    dest: '/etc/chrony/chrony.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart chrony' ]