---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Import global handlers
  import_role:
    name: 'global_handlers'

- name: Ensure that configuration is supported
  assert:
    that: not ntp__daemon or ntp__daemon in [ 'chrony', 'ntpd', 'ntpdate', 'openntpd', 'systemd-timesyncd' ]

- name: Ensure that alternative daemons/programs are not installed
  apt:
    name: '{{ ntp__purge_packages | flatten }}'
    state: 'absent'
    purge: True
  register: ntp__register_apt_purge
  until: ntp__register_apt_purge is succeeded

  # Installs either ntpdate, NTPd, chrony or OpenNTPd on all hosts except inside containers
- name: Install NTP service
  include_tasks: install.yml
  when: ntp__daemon_enabled | bool

- name: Make sure that Ansible local facts directory exists
  ansible.builtin.file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save ntp local facts
  ansible.builtin.template:
    src: 'etc/ansible/facts.d/ntp.fact.j2'
    dest: '/etc/ansible/facts.d/ntp.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  tags: [ 'meta::facts' ]

  
...