---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

# The order of the imports affects the execution order of handlers.

- name: Import Meta
  ansible.builtin.import_tasks: 'meta.yml'

- name: Import NTP
  ansible.builtin.import_tasks: 'ntp.yml'

- name: Import LLDPD
  ansible.builtin.import_tasks: 'lldpd.yml'

- name: Import Hddtemp
  ansible.builtin.import_tasks: 'hddtemp.yml'

- name: Import Smart tools
  ansible.builtin.import_tasks: 'smartmontools.yml'
