---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Refresh host facts
  ansible.builtin.setup:

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: True
  listen:
    - 'Reload service manager'
  when: ansible_service_mgr == 'systemd'

- name: Create temporary files with systemd-tmpfiles
  ansible.builtin.command: 'systemd-tmpfiles --create'
  listen:
    - 'Create temporary files'
  when: ansible_service_mgr == 'systemd'

- name: Reboot after full upgrade
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible after full packages upgrade"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
