---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart openntpd
  ansible.builtin.service:
    name: 'openntpd'
    state: 'restarted'
  when: not ansible_check_mode

- name: Restart ntp
  ansible.builtin.service:
    name: 'ntp'
    state: 'restarted'
  when: ntp__daemon == 'ntpd'

- name: Restart systemd-timesyncd
  ansible.builtin.service:
    name: 'systemd-timesyncd'
    state: 'restarted'

- name: Restart chrony
  ansible.builtin.service:
    name: 'chrony'
    state: 'restarted'
