---

- name: Test if additional_disks is set correctly
  ansible.builtin.assert:
    that:
      - mount_disks_to_manage
      - mount_disks_to_manage|length > 0
    quiet: yes

- name: Test if item.path in additional_disks is set correctly
  ansible.builtin.assert:
    that:
      - item.path is defined
      - item.path is string
    quiet: yes
  loop: "{{ mount_disks_to_manage }}"
  loop_control:
    label: "{{ item.path }}"

- name: Test if item.state in additional_disks is set correctly
  ansible.builtin.assert:
    that:
      - item.state is string
      - item.state in [ "absent", "mounted", "present", "remounted", "unmounted" ]
    quiet: yes
  when:
    - item.state is defined
  loop: "{{ mount_disks_to_manage }}"
  loop_control:
    label: "{{ item.path }}"