---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Prepare CI pipeline environment
on: [ 'push', 'pull_request' ]

runs:
  using: 'composite'
  steps:

    - name: Add ~/.local/bin to $PATH
      run: 'printf "%s/.local/bin\n" "${HOME}" >> ${GITHUB_PATH}'
      shell: 'bash'

    - name: Prepare test environment
      run: |
        sudo apt-get -qq update
        sudo apt-get remove --purge -yq ansible python python2.7 python2.7-minimal
        pip3 install --user --upgrade pip wheel setuptools
        pip3 install --user --upgrade Jinja2 ansible
        pip3 install --user .
      shell: 'bash'
