---
# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Manage HP ProLiant MicroServer Gen8 servers
  collections: [ 'progeekro.bootstrap', 'progeekro.roles01',
                 'progeekro.roles02', 'progeekro.roles03' ]
  hosts: [ 'service_hp_microserver_gen8' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: apt
      tags: [ 'role::apt', 'skip::apt' ]
      apt__dependent_keys:
        - '{{ hp__dependent_ams_repositoy_key }}'
      apt__dependent_repositories:
        - '{{ hp__dependent_mcp_repo }}'

    - role: hp_microserver_gen8
      tags: [ 'role::hp_microserver_gen8', 'skip::hp_microserver_gen8' ]