---
# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Manage local disks and parted management
  collections: [ 'progeekro.bootstrap', 'progeekro.roles01',
                 'progeekro.roles02', 'progeekro.roles03' ]
  hosts: [ 'service_parted' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: parted
      tags: [ 'role::parted', 'skip::parted' ]