---

- name: Manage Advanced Package Manager
  collections: [ 'progeek.bootstrap' ]
  hosts: [ 'all_hosts', 'service_apt' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: apt
      tags: [ 'role::apt', 'skip::apt' ]