---

- name: Reboot hosts
  hosts: [ 'all_hosts' ]
  collections: [ 'progeekro.bootstrap', 'progeekro.roles01',
                 'progeekro.roles02', 'progeekro.roles03' ]
  become: True

  gather_facts: False

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: reboot
      tags: [ 'role::reboot', 'skip::reboot' ]