---

- name: Remove K3S service files, binaries and data
  collections: [ 'progeekro.k3s', 'progeekro.roles01',
                 'progeekro.roles02', 'progeekro.roles03' ]
  hosts: [ 'k3s_cluster' ]
  gather_facts: True
  become: True
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:
    - role: k3s-reset
      tags: [ 'progeek.k3s-reset', 'skip::progeek.k3s-reset' ]
