---
# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Upgrade a machine using APT
  collections: [ 'progeekro.bootstrap', 'progeekro.roles01',
                 'progeekro.roles02', 'progeekro.roles03' ]
  hosts: [ 'all_hosts' ]
  become: True
  gather_facts: False

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Upgrade safe packages with refreshed cache
      ansible.builtin.apt:
        update_cache: True
        upgrade: 'safe'
