---

- name: Upgrade a machine using APT
  hosts: [ 'all_hosts' ]
  collections: [ 'progeekro.bootstrap' ]
  become: True
  gather_facts: False

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: Upgrade safe packages with refreshed cache
      ansible.builtin.apt:
        update_cache: True
        upgrade: 'safe'