---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Setup fact with values loaded from host variables  # noqa var-naming
  ansible.builtin.set_fact:
    "{{ select_hostvars_query.fact_name }}": >-
      {{ lookup('template', 'hostvars.yml.j2') | from_yaml }}
  when: select_hostvars_query is defined
  tags:
    - role::select_hostvars
