---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Import global handlers
  ansible.builtin.import_role:
    name: 'global_handlers'

- name: Install the APT packages
  ansible.builtin.apt:
    name: '{{ hp__t620_packages }}'
    state: "{{ 'latest' if hp__t620_enabled | bool else 'absent' }}"
    update_cache: yes
  register: register_apt_packages
  until: register_apt_packages is succeeded

- name: Install the DEB packages
  ansible.builtin.apt:
    deb: '{{ item }}'
  with_items: '{{ hp__t620_deb_packages }}'
  register: register_deb_packages
  until: register_deb_packages is succeeded
