---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Import global handlers
  ansible.builtin.import_role:
    name: 'global_handlers'

- name: Install HP MCP packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ 'latest' if hp__microserver_gen8_enabled | bool else 'absent' }}"
  with_items: "{{ hp__ams_packages }}"
  register: hp__register_base_packages
  until: hp__register_base_packages is succeeded

- name: Install binary firmware for QLogic
  ansible.builtin.apt:
    name: "{{ hp__qlogic_network_driver_packages }}"
    state: present
    update_cache: yes
  register: hp__register_base_binary
  until: hp__register_base_binary is succeeded
  when: hp__qlogic_network_driver_enabled | bool
