---
# Copyright (C) 2021-2022 Zaharia Constantin <constantin.zaharia@progeek.ro>
# Copyright (C) 2021-2022 ProGeek <https://progeek.ro>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Import Parted role
  import_playbook: ../service/parted.yml

- name: Import Mount role
  import_playbook: ../service/mount.yml
