---

- name: Refresh host facts
  setup:

- name: Reload systemd daemon
  systemd:
    daemon_reload: True
  listen:
    - 'Reload service manager'
  when: ansible_service_mgr == 'systemd'

- name: Create temporary files with systemd-tmpfiles
  command: 'systemd-tmpfiles --create'
  listen:
    - 'Create temporary files'
  when: ansible_service_mgr == 'systemd'

- name: Reboot after full upgrade
  reboot:
    msg: "Reboot initiated by Ansible after full packages upgrade"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime