---

- name: Restart openntpd
  service:
    name: 'openntpd'
    state: 'restarted'
  when: not ansible_check_mode

- name: Restart ntp
  service:
    name: 'ntp'
    state: 'restarted'
  when: ntp__daemon == 'ntpd'

- name: Restart systemd-timesyncd
  service:
    name: 'systemd-timesyncd'
    state: 'restarted'

- name: Restart chrony
  service:
    name: 'chrony'
    state: 'restarted'